#!/usr/bin/env bash
# Script that manages its PID file and reacts to signals

PIDFILE="/var/run/myscript.pid"

mkdir -p /var/run 2>/dev/null

echo "$$" > "$PIDFILE"

trap 'echo "Y U no love me?!";' INT
trap 'echo "I hate the kill command"; rm -f "$PIDFILE"; exit 0;' TERM
trap 'rm -f "$PIDFILE"; exit 0;' QUIT

while true
do
  echo "To infinity and beyond"
  sleep 2
done
